apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kitchen-log.fullname" . }}-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "kitchen-log.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ include "kitchen-log.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      {{- include "kitchen-log.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "kitchen-log.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: mysql
        image: "{{ .Values.image.mysql.repository }}:{{ .Values.image.mysql.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "kitchen-log.fullname" . }}-mysql
              key: rootPassword
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "kitchen-log.fullname" . }}-mysql
              key: password
        - name: TZ
          value: {{ .Values.timezone | quote }}
        args:
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_unicode_ci"
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources.mysql | nindent 12 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      {{- if not .Values.mysql.persistence.enabled }}
      volumes:
      - name: data
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.mysql.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.mysql.persistence.size | quote }}
  {{- end }}