{{- if .Values.storageClass.create }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.standard.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    {{- include "kitchen-log.labels" . | nindent 4 }}
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
  fstype: ext4
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.premium.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    {{- include "kitchen-log.labels" . | nindent 4 }}
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
  fstype: ext4
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
{{- end }}